### ISSUE TITLE
Update Documentation With New Package Name

### ISSUE THREAD

**Issue by 0xmachos** [univ-of-utah-marriott-library-apple/python-jamf#81]
Running one of my existing Jupyter notebooks I got the following error
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 2
      1 # Imports
----> 2 import jamf
      3 import datetime
      4 from dateutil.relativedelta import relativedelta, FR

ModuleNotFoundError: No module named 'jamf'
```

It appears that in https://github.com/univ-of-utah-marriott-library-apple/python-jamf/commit/220f88efa7f6ab3540f511021452988b9c89a7d6 you renamed the package from `jamf` to `python_jamf`. This change has appeared in version `0.9.0` which was [published on pypi on December 11th](https://pypi.org/project/python-jamf/#history).

All I had to do to get my code running again was:  

* `import jamf` > `import python_jamf`
* `api = jamf.Api()` > `api = python_jamf.Api()`

I'd be happy to make a PR if the change in documentation is as simple as my experience above?

**Comment by homebysix** [comment]
This explains why our python-jamf automation broke on Dec 12. This sort of breaking change would warrant a change from v0.x.x to v1.x.x in my opinion, along with some deprecation warnings before the change occurs.

**Comment by magnusviri** [comment]
Eeek, sorry about that. Honestly, I wasn't sure how to implement this change. I did ask about this on the jctl Slack channel but didn't get any replies. I've been kind of afraid of this change but it's been so long since we've made a release so I finally pushed myself to just release it. If you guys have suggestions how to fix this now and how to fix this in the future I'd love the feedback. We're using a github action to automate the release to pypi and I can't see how to do a release candidate with our setup. I've been trying to figure out if there's a better way.
